version: '3'
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    restart: always

  app:
    build:
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    depends_on: 
      - redis


    