version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    restart: always
    networks:
      - redis-net

  app:
    build:
      context: ./build/service/
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    depends_on: 
      - redis
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge